# Generated by Django 6.1.1 on 2026-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="recurrence",
            field=models.CharField(
                choices=[("none", "None"), ("daily", "Daily"), ("weekly", "Weekly")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="weekdays",
            field=models.CharField(blank=True, default="", max_length=13),
        ),
    ]
